import type { CommunityComment, CommunityPost, CommunityProfile } from '@/types/community';

export const communityProfiles: CommunityProfile[] = [
  {
    id: 'u1',
    username: 'maya-endpoint',
    displayName: 'Maya Ortiz',
    title: 'Senior Endpoint Engineer',
    company: 'Northwind Health',
    skills: ['Intune', 'Defender', 'Windows Autopilot'],
    role: 'VERIFIED_PROFESSIONAL',
    reputation: 4820,
    acceptedAnswersCount: 42,
    postsCount: 118,
  },
  {
    id: 'u2',
    username: 'cloudpatch-admin',
    displayName: 'Ren Chen',
    title: 'Cloud Operations Lead',
    company: 'Contoso Manufacturing',
    skills: ['Azure', 'M365', 'Patch Management'],
    role: 'MODERATOR',
    reputation: 7190,
    acceptedAnswersCount: 67,
    postsCount: 203,
  },
  {
    id: 'u3',
    username: 'secops-jordan',
    displayName: 'Jordan Malik',
    title: 'Security Analyst',
    skills: ['Vulnerabilities', 'Identity', 'EDR'],
    role: 'VERIFIED_PROFESSIONAL',
    reputation: 3910,
    acceptedAnswersCount: 29,
    postsCount: 91,
  },
];

export const communityComments: CommunityComment[] = [
  {
    id: 'c1',
    postId: 'p1',
    body:
      'We saw this after the service health advisory rolled out. Confirm the Intune Management Extension is on 1.80+ and force a device sync after clearing stale EnrollmentStatusTracking CSP state.',
    author: communityProfiles[0],
    voteCount: 38,
    isAccepted: true,
    isModeratorNote: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    replies: [
      {
        id: 'c1-r1',
        postId: 'p1',
        parentId: 'c1',
        body: 'Confirmed. Clearing the stale ESP registry keys and syncing fixed three pilot devices.',
        author: communityProfiles[2],
        voteCount: 7,
        isAccepted: false,
        isModeratorNote: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
        replies: [],
      },
    ],
  },
  {
    id: 'c2',
    postId: 'p2',
    body: 'Moderator note: do not disable conditional access globally. Use a scoped break-glass exclusion and document the window.',
    author: communityProfiles[1],
    voteCount: 22,
    isAccepted: false,
    isModeratorNote: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    replies: [],
  },
];

export const communityPosts: CommunityPost[] = [
  {
    id: 'p1',
    slug: 'intune-autopilot-esp-hangs-after-weekend-update',
    title: 'Intune Autopilot ESP hangs after weekend update on Windows 11 23H2',
    body:
      'Multiple newly imaged laptops are stuck on Account setup during ESP. Network is clean, apps are assigned, and the issue started after the latest Microsoft 365 service notices. Has anyone confirmed a reliable fix without wiping devices?',
    type: 'QUESTION',
    category: 'Intune',
    tags: ['Intune', 'Autopilot', 'Windows 11', 'ESP'],
    affectedVendor: 'Microsoft',
    affectedProduct: 'Microsoft Intune',
    environment: {
      tenant: 'Hybrid Entra joined',
      os: 'Windows 11 23H2',
      deviceCount: '37 affected',
    },
    severity: 'HIGH',
    status: 'SOLVED',
    author: communityProfiles[2],
    voteCount: 146,
    commentCount: 18,
    acceptedSolution: communityComments[0],
    createdAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: 'p2',
    slug: 'microsoft-365-sign-in-failures-field-observations',
    title: 'Microsoft 365 sign-in failures: field observations and safe workarounds',
    body:
      'We are correlating reports from multiple regions. Users can reach Teams web but Outlook desktop is intermittently failing token refresh. Share tenant region, auth method, and mitigation attempts.',
    type: 'INCIDENT',
    category: 'Microsoft 365',
    tags: ['Microsoft 365', 'Identity', 'Outage', 'Outlook'],
    affectedVendor: 'Microsoft',
    affectedProduct: 'Entra ID / Microsoft 365',
    environment: {
      auth: 'Conditional Access + MFA',
      clients: 'Outlook desktop, Teams web',
    },
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    author: communityProfiles[1],
    voteCount: 302,
    commentCount: 41,
    createdAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
  },
  {
    id: 'p3',
    slug: 'defender-for-endpoint-tamper-protection-policy-conflict',
    title: 'Verified fix: Defender for Endpoint tamper protection conflict with legacy GPO',
    body:
      'If MDE tamper protection flips back after Intune policy success, check for legacy Security Baseline GPO setting DisableAntiSpyware. Removing that stale policy and forcing gpupdate resolved the conflict across our fleet.',
    type: 'FIX',
    category: 'Endpoint',
    tags: ['Defender', 'Endpoint', 'GPO', 'Verified Fix'],
    affectedVendor: 'Microsoft',
    affectedProduct: 'Defender for Endpoint',
    environment: {
      os: 'Windows 10/11 mixed',
      management: 'Intune + legacy GPO',
    },
    severity: 'MEDIUM',
    status: 'SOLVED',
    author: communityProfiles[0],
    voteCount: 214,
    commentCount: 9,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
];
